name: GCP CI

on:
  push:
    branches: ['**']
  pull_request:
  workflow_dispatch: {}

jobs:
  gcp-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    env:
      GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
      FIRESTORE_COLLECTION: ${{ secrets.FIRESTORE_COLLECTION || 'visitors' }}
      CLOUD_RUN_URL: ${{ secrets.CLOUD_RUN_URL }}
      CLOUD_RUN_HEALTH_PATH: ${{ secrets.CLOUD_RUN_HEALTH_PATH || '/healthz' }}
      CLOUD_RUN_DETECT_PATH: ${{ secrets.CLOUD_RUN_DETECT_PATH }}
      ESP32_IMAGE_URL: ${{ secrets.ESP32_IMAGE_URL }}
      # ⚠️ 這裡先不要用 runner.temp，稍後用 step 寫入 GITHUB_ENV
    steps:
      - uses: actions/checkout@v4

      # 先把 GOOGLE_APPLICATION_CREDENTIALS 寫到環境變數（用 $RUNNER_TEMP）
      - name: Export GOOGLE_APPLICATION_CREDENTIALS
        shell: bash
        run: echo "GOOGLE_APPLICATION_CREDENTIALS=$RUNNER_TEMP/gcp-key.json" >> $GITHUB_ENV

      - name: Write GCP service account key
        shell: bash
        run: |
          if [[ -z "${{ secrets.GCP_SA_KEY }}" ]]; then
            echo "❌ Missing secret GCP_SA_KEY"; exit 1;
          fi
          echo "${{ secrets.GCP_SA_KEY }}" > "$RUNNER_TEMP/gcp-key.json"
          echo "✅ SA key written to $RUNNER_TEMP/gcp-key.json"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install base deps
        run: |
          python -m pip install --upgrade pip
          pip install google-cloud-vision google-cloud-firestore requests numpy \
                     google-auth google-auth-transport-requests

      - name: Connectivity tests
        run: python scripts/gcp_connect_test.py

      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: gcp-logs
          path: |
            gcp_test.log
            vision_test.log
            firestore_test.log
            cloudrun_test.log
          if-no-files-found: warn   # ← 一定要在 with: 底下，而且是 v4
