name: Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]
    paths:
      - "api.py"
      - "requirements.txt"
      - ".github/workflows/deploy-cloudrun.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      SERVICE_NAME: esp32-cam-jim
      REGION: asia-east1
      PROJECT_ID: ${{ secrets.GCP_PROJECT }}
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          export_environment_variables: true

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: Deploy (source-based)
        run: |
          gcloud run deploy "$SERVICE_NAME" \
            --source . \
            --region "$REGION" \
            --allow-unauthenticated
