name: Manual OIDC Check

on:
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      PROJECT_ID: esp32cam-472912
      REGION: asia-east1
      EXPECTED_ACCOUNT: codex-ci@esp32cam-472912.iam.gserviceaccount.com
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate via OIDC
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/665759721336/locations/global/workloadIdentityPools/github-pool/providers/github-actions
          service_account: codex-ci@esp32cam-472912.iam.gserviceaccount.com

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      - name: Validate service account
        run: |
          set -euo pipefail
          gcloud auth list --filter=status:ACTIVE
          ACTIVE_ACCOUNT="$(gcloud config get-value account)"
          echo "Active SA = ${ACTIVE_ACCOUNT}"
          if [ "${ACTIVE_ACCOUNT}" != "${EXPECTED_ACCOUNT}" ]; then
            echo "::error::Active account (${ACTIVE_ACCOUNT}) does not match expected (${EXPECTED_ACCOUNT})"
            exit 1
          fi
          gcloud ai index-endpoints list --region="${REGION}" --project="${PROJECT_ID}"
