name: manual-oidc-check

on:
  workflow_dispatch:

jobs:
  oidc-check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    # 關鍵：一定要有 id-token: write，否則 OIDC 不會簽出臨時憑證
    permissions:
      id-token: write
      contents: read

    env:
      PROJECT_ID: esp32cam-472912
      REGION: asia-east1
      SERVICE_ACCOUNT: codex-ci@esp32cam-472912.iam.gserviceaccount.com
      WIP: projects/665759721336/locations/global/workloadIdentityPools/github-pool/providers/github-actions

    steps:
      - uses: actions/checkout@v4

      - name: Auth via OIDC
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.WIP }}
          service_account: ${{ env.SERVICE_ACCOUNT }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>= 477.0.0'

      - name: Show active account (should be the SA)
        run: |
          gcloud auth list --filter=status:ACTIVE
          gcloud config get-value account
          gcloud projects describe "$PROJECT_ID" --format='value(projectNumber)'

      - name: Sanity check - list resources
        run: |
          echo "List GCS buckets (need storage viewer at least)"
          gcloud storage buckets list --project "$PROJECT_ID" --format='value(name)' | head -n 10 || true

          echo "List Vertex Index Endpoints (need aiplatform.user)"
          gcloud ai index-endpoints list --project "$PROJECT_ID" --region "$REGION" --format='table(name,displayName)'

      - name: Final assertion
        run: |
          ACCT=$(gcloud config get-value account)
          if [[ "$ACCT" != *"${SERVICE_ACCOUNT}"* ]]; then
            echo "::error::Active account is not the expected service account: $ACCT"
            exit 1
          fi
          echo "✅ OIDC looks good. Active SA: $ACCT"
