name: WIF Smoke Test
on: { workflow_dispatch: {} }

permissions:
  id-token: write
  contents: read

env:
  PROJECT_ID: esp32cam-472912

jobs:
  auth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Auth to GCP via OIDC
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}
          create_credentials_file: true
          export_environment_variables: true

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          version: '>= 477.0.0'

      - name: Who am I?
        shell: bash
        run: |
          set -euo pipefail
          gcloud auth list
          gcloud config list project
          gcloud projects describe "$PROJECT_ID" --format='value(projectNumber,projectId)'
