name: WIF Smoke Test
on: { workflow_dispatch: {} }

permissions:
  id-token: write
  contents: read

jobs:
  auth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Auth to GCP via OIDC
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Who am I?
        run: |
          gcloud auth list
          gcloud config list project
          gcloud projects describe esp32cam-472912 --format='value(projectNumber,projectId)'

                - name: GCS read/write check
        run: |
          gsutil ls gs://esp32cam-472912-vertex-data | head -n 5
          echo "test $(date)" > /tmp/ci.txt
          gsutil cp /tmp/ci.txt gs://esp32cam-472912-faces/new_photos/ci_$(date +%s).txt

      - name: Vertex list check
        run: |
          gcloud ai pipeline-jobs list --region=asia-east1 --limit=3

      - name: Cloud Run /health
        env:
          SERVICE_URL: ${{ vars.SERVICE_URL }}
        run: |
          curl -fS "${SERVICE_URL%/}/health" -i

